ownerID: "" # Discord ID of owner
apiBible: "" # API.Bible key
dry: false # should namefetcher skip itself?
letsEncryptEmail: "" # Email for Let's Encrypt notifications.
decryptionKey: "" # Applicable decryption key
encryptedFiles:
  - "" # list all tar.zst.gpg files by name here