name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: cd tests && go test -json -v ./... > results.json
    
    - name: Annotations
      uses: guyarb/golang-test-annotations@v0.3.0
      with:
        test-results: tests/results.json
